config/routes.rb
Blog1::Application.routes.draw do
  root 'welcome#index'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	 def index 
	 		 @users = User.all
	 end
	 
	 def new
	 	@user = User.new
	 end

	 def create
	 	@user = User.new(as_params)
		@user.save
		redirect_to users_path
	 end

	 def edit
	 	@user = User.find(params[:id])
	 end

	 def update
	 	@user = User.find(params[:id])
		@user.update_attributes(as_params)
		redirect_to users_path
	 end
	 def show
	 end
	 def destroy
	 	@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	 end

	 private
		def as_params
			params.require(:user).permit(:name, :age, :phone, :email, :city)
		end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render "/shared/metatags" %>
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400" rel="stylesheet" />
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_metatags.html.erb
		<title>Astral by HTML5 Up!</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />

app/views/users/edit.html.erb
<table>
	<%= form_for @user, url: user_path(@user) do |f| %>
		<tr><td><%= f.label :name %>
		<td><%= f.text_field :name, autofocus: true, required: true %>

		<tr><td><%= f.label :age %>
		<td><%= f.text_field :age %>

		<tr><td><%= f.label :phone %>
		<td><%= f.text_field :phone %>

		<tr><td><%= f.label :city %>
		<td><%= f.text_field :city %>

		<tr><td><%= f.label :email %>
		<td><%= f.email_field :email, required: true %>

		<tr><td><%= f.submit :Submit %>
	<% end %>
</table>

app/views/users/index.html.erb
<table>
	<tr><td><%= link_to "New", new_user_path %>
	<tr><td>ID<td>Name<td>Email<td>Phone<td>City<td>Age<td>Actions
	<% @users.each do |user| %>
	<tr>
		<td><%= user.id %>
		<td><%= user.name %>
		<td><%= user.email %>
		<td><%= user.phone %>
		<td><%= user.city %>
		<td><%= user.age %>
		<td><%= link_to "Edit", edit_user_path(user) %> &nbsp <%= link_to "Delete", user_path(user), method: :delete %>
	<% end %>
</table>

app/views/users/new.html.erb
<table>
	<%= form_for @user, url: users_path do |f| %>
		<tr><td><%= f.label :name %>
		<td><%= f.text_field :name, autofocus: true, required: true %>

		<tr><td><%= f.label :age %>
		<td><%= f.text_field :age %>

		<tr><td><%= f.label :phone %>
		<td><%= f.text_field :phone %>

		<tr><td><%= f.label :city %>
		<td><%= f.text_field :city %>

		<tr><td><%= f.label :email %>
		<td><%= f.email_field :email, required: true %>

		<tr><td><%= f.submit :Submit %>
	<% end %>
</table>

app/views/welcome/index.html.erb
		<!-- Wrapper-->
			<div id="wrapper">
				
				<!-- Nav -->
					<nav id="nav">
						<a href="#me" class="icon icon-user active"><span>Me</span></a>
						<a href="#work" class="icon icon-folder"><span>Work</span></a>
						<a href="#email" class="icon icon-mail"><span>Email Me</span></a>
						<a href="http://twitter.com/n33co" class="icon icon-twitter"><span>Twitter</span></a>
					</nav>

				<!-- Main -->
					<div id="main">
						
						<!-- Me -->
							<article id="me" class="panel">
								<header>
									<h1>Jane Doe</h1>
									<span class="byline">Senior Astral Projectionist</span>
								</header>
								<a href="#work" class="jumplink pic">
									<span class="jumplink arrow icon icon-right"><span>See my work</span></span>
									<img src="/assets/me.jpg" alt="" />
								</a>
							</article>

						<!-- Work --> 
							<article id="work" class="panel">
								<header>
									<h2>Work</h2>
								</header>
								<p>
									Phasellus enim sapien, blandit ullamcorper elementum eu, condimentum eu elit. 
									Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia 
									luctus elit eget interdum.
								</p>
								<section class="5grid is-gallery">
									<div class="row">
										<div class="4u">
											<a href="http://flypixel.com/knob/3495684098026313" class="image image-full"><img src="/assets/1.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/contact-login-form/8829734266026310" class="image image-full"><img src="/assets/2.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/wallpaper-pack/3755398966026313" class="image image-full"><img src="/assets/3.jpg" alt=""></a>
										</div>
									</div>
									<div class="row">
										<div class="4u">
											<a href="http://flypixel.com/44-shades-of-free-icons/8268508056006318" class="image image-full"><img src="/assets/4.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/flip-clock/3655053956026317" class="image image-full"><img src="/assets/5.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/dropdown/5290304620795313" class="image image-full"><img src="/assets/6.jpg" alt=""></a>
										</div>
									</div>
									<div class="row">
										<div class="4u">
											<a href="http://flypixel.com/pie-charts/1759361594616314" class="image image-full"><img src="/assets/7.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/sliding-selector-bar/7042935581006315" class="image image-full"><img src="/assets/8.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/dark-as-hell-ui/5418809286006313" class="image image-full"><img src="/assets/9.jpg" alt=""></a>
										</div>
									</div>
									<div class="row">
										<div class="4u">
											<a href="http://flypixel.com/cityscape/9803996277226316" class="image image-full"><img src="/assets/10.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/dropdown/8259263378026313" class="image image-full"><img src="/assets/11.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/wood-ui-kit/3574765984616310" class="image image-full"><img src="/assets/12.jpg" alt=""></a>
										</div>
									</div>
									<div class="row">
										<div class="4u">
											<a href="http://flypixel.com/upload-button/9737964647895311" class="image image-full"><img src="/assets/13.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/collapsible-menunavigation/5743165610406316" class="image image-full"><img src="/assets/14.jpg" alt=""></a>
										</div>
										<div class="4u">
											<a href="http://flypixel.com/3d-button/5506786525606318" class="image image-full"><img src="/assets/15.jpg" alt=""></a>
										</div>
									</div>
								</section>
							</article>

						<!-- Email -->
							<article id="email" class="panel">
								<header>
									<h2>Email Me</h2>
								</header>
								<form action="#" method="post">
									<div class="5grid">
										<div class="row">
											<div class="6u">
												<input type="text" class="text" name="name" placeholder="Name" />
											</div>
											<div class="6u">
												<input type="text" class="text" name="email" placeholder="Email" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<input type="text" class="text" name="subject" placeholder="Subject" />
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<textarea name="message" placeholder="Message"></textarea>
											</div>
										</div>
										<div class="row">
											<div class="12u">
												<input type="submit" class="button" value="Send Message" />
											</div>
										</div>
									</div>
								</form>
							</article>

					</div>
		
				<!-- Footer -->
					<div id="footer">
						<ul class="links">
							<li>&copy; Jane Doe</li>
							<li>Images : <a href="http://fotogrph.com/">fotogrph</a></li>
							<li>Design : <a href="http://html5up.net/">HTML5 Up!</a></li>
						</ul>
					</div>